// Generated by scripts/upload-piper-audio.mjs.
// Sentence recordings are loaded from public WebM/Opus sprites when available.
export const PIPER_SENTENCE_AUDIO_BASE_URL = "";
export const PIPER_SENTENCE_AUDIO_MIME_TYPE = "audio/webm; codecs=\"opus\"";
export const PIPER_SENTENCE_AUDIO_SPRITE_PREFIX = "kokoro-martin-sentence";
export const piperSentenceAudioClips: Record<string, readonly [number, number, number]> = {};
